version: '3.8'

services:
  db:
    image: postgis/postgis:13-3.1
    container_name: geodjango-db
    environment:
      POSTGRES_DB: geodjango
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
