repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.8.0'
    hooks:
    -   id: ruff
        args:
        - --fix
    -   id: ruff-format
-   repo: https://github.com/rtts/djhtml
    rev: '3.0.7'
    hooks:
    -   id: djhtml
        entry: djhtml --tabwidth 2
    -   id: djcss
    -   id: djjs
