repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.2
    hooks:
    -   id: ruff
        args:
        - --fix
    -   id: ruff-format
-   repo: https://github.com/rtts/djhtml
    rev: 3.0.6
    hooks:
    -   id: djhtml
    -   id: djcss
    -   id: djjs
