

services:
  web: &sync
    develop:
      watch:
        - action: sync
          path: .
          target: /app/
          ignore:
            - .venv/
        - action: rebuild
          path: ./poetry.lock

  celery_worker:
    <<: *sync

  celery_beat:
    <<: *sync


