services:
  web: &sync
    develop:
      watch:
        - action: sync
          path: .
          target: /app/
          ignore:
            - .venv/
        - action: rebuild
          path: ./poetry.lock


    image: hackathonscanada:latest
    container_name: web

  celery_worker:
    <<: *sync
    image: hackathonscanada:latest
    container_name: celery_worker

  celery_beat:
    <<: *sync
    image: hackathonscanada:latest
    container_name: celery_beat


