# Generated by Django 5.1.4 on 2024-12-21 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='hybrid',
            field=models.CharField(choices=[('I', 'In-Person'), ('O', 'Online'), ('H', 'Hybrid')], default='I', help_text='Location of the hackathon, I for in-person, V for virtual, H for hybrid', max_length=1),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='maximum_education_level',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Middle School'), (1, 'High School'), (2, 'University/College'), (3, 'Graduated University/College'), (4, 'Other'), (5, 'Any/All')], help_text="Maximum education level required to participate, set to Any/All if there is no maximum education level and don't set if unknown", null=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='minimum_education_level',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Middle School'), (1, 'High School'), (2, 'University/College'), (3, 'Graduated University/College'), (4, 'Other'), (5, 'Any/All')], help_text="Minimum education level required to participate, set to Any/All if there is no minimum education level and don't set if unknown", null=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='scrape_source',
            field=models.CharField(choices=[('mlh', 'MLH'), ('dev', 'Devpost'), ('eth', 'ETHGlobal'), ('hcl', 'Hack Club'), ('na', 'Not Applicable')], default='na', max_length=3),
        ),
        migrations.AddField(
            model_name='hacker',
            name='education',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Middle School'), (1, 'High School'), (2, 'University/College'), (3, 'Graduated University/College'), (4, 'Other')], help_text='Your current education level e.g. High School, University, etc.', null=True),
        ),
    ]
