# Generated by Django 5.1.4 on 2024-12-25 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='end_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='is_public',
            field=models.BooleanField(db_index=True, default=False, help_text='Is the hackathon visible to all users'),
        ),
        migrations.AlterField(
            model_name='hackathonlocation',
            name='name',
            field=models.CharField(blank=True, db_index=True, help_text='Where the hackathon is located (e.g. Buringlont, Ontario)', max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='hackathon',
            index=models.Index(fields=['end_date', 'is_public'], name='hkthn_end_date_and_public_idx'),
        ),
    ]
