# Generated by Django 5.0.4 on 2024-04-13 18:18

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "color",
                    models.CharField(
                        default=core.models.get_random_color,
                        help_text="Color of the category in hex format e.g. #FF0000",
                        max_length=7,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AddField(
            model_name="hackathon",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hackathon",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hackathons",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="hackathon",
            name="curators",
            field=models.ManyToManyField(
                related_name="curated_hackathons", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="hackathon",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="hacker",
            name="saved",
            field=models.ManyToManyField(
                help_text="Hackathons the user is interested in and wants updates about.",
                related_name="interested_users",
                to="core.hackathon",
            ),
        ),
        migrations.AddField(
            model_name="hackathon",
            name="categories",
            field=models.ManyToManyField(related_name="hackathons", to="core.category"),
        ),
        migrations.AddField(
            model_name="hacker",
            name="saved_categories",
            field=models.ManyToManyField(
                help_text="Categories the user is interested in and wants updates when new hackathons meeting this critera are created.",
                related_name="interested_users",
                to="core.category",
            ),
        ),
    ]
