# Generated by Django 5.1.4 on 2024-12-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='scrape_source',
            field=models.CharField(choices=[('mlh', 'MLH'), ('dev', 'Devpost'), ('eth', 'ETHGlobal'), ('hcl', 'Hack Club'), ('na', 'Not Applicable')], default='na', max_length=255),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='source',
            field=models.CharField(choices=[('SCR', 'Scraped'), ('USR', 'User Submitted'), ('PRT', 'Partner')], default='USR', max_length=255),
        ),
    ]
