# Generated by Django 5.1.4 on 2024-12-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_hackathon_scrape_source_alter_hackathon_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathonlocation',
            name='country',
            field=models.CharField(blank=True, help_text='what country', max_length=255, null=True),
        ),
    ]
