# Generated by Django 5.1.4 on 2024-12-23 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_hackathonlocation_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='bg_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='hackathon_images'),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='fg_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='hackathon_images'),
        ),
    ]
