# Generated by Django 5.0.7 on 2024-07-15 01:25

import core.models
import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_remove_notificationpolicy_weekly_or_monthly_not_both_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HackathonLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Where the hackathon is located (e.g. University of Toronto)",
                        max_length=255,
                    ),
                ),
                ("country", django_countries.fields.CountryField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=16, max_digits=22)),
                ("longitude", models.DecimalField(decimal_places=16, max_digits=22)),
            ],
        ),
        migrations.AlterModelManagers(
            name="hacker",
            managers=[
                ("objects", core.models.Notifiable()),
            ],
        ),
        migrations.RemoveField(
            model_name="hackathon",
            name="country",
        ),
        migrations.AddField(
            model_name="hackathon",
            name="location",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="hackathons",
                to="core.hackathonlocation",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hackathonlocation",
            name="location",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="location",
                to="core.location",
            ),
        ),
    ]
