# Generated by Django 5.0.7 on 2024-08-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_hackathonlocation_location_alter_hacker_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hackathon",
            name="review_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("pending", "Pending"),
                    ("requesting_changes", "Requesting Changes"),
                ],
                default="pending",
                help_text="Status of the review process",
                max_length=255,
            ),
        ),
    ]
