# Generated by Django 5.1 on 2024-10-31 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_curatorrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='hacker',
            name='birthday',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hacker',
            name='personal_website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
