# Generated by Django 5.1 on 2024-11-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hacker',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hacker',
            name='education',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Middle School'), (1, 'High School'), (2, 'University/College'), (3, 'Graduated University/College'), (4, 'Other')], help_text='Your current education level e.g. High School, University, etc.', null=True),
        ),
    ]
