# Generated by Django 5.1 on 2024-11-18 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_hacker_birthday_alter_hacker_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackathon',
            name='image',
        ),
        migrations.AddField(
            model_name='hackathon',
            name='bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='hackathon_images'),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='custom_info',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='fg_image',
            field=models.ImageField(blank=True, null=True, upload_to='hackathon_images'),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='freeze_data',
            field=models.BooleanField(default=False, help_text='Set to True to not update any details using scraped data. Use if you get accurate details directly from the hackathon organizers.'),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='hybrid',
            field=models.CharField(choices=[('I', 'In-Person'), ('O', 'Online'), ('H', 'Hybrid')], default='I', help_text='Location of the hackathon, I for in-person, V for virtual, H for hybrid', max_length=1),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='is_diversity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='is_nonenglish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='is_over18',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='is_restricted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='is_web3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='last_scraped',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='id',
            field=models.CharField(editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='source',
            field=models.CharField(choices=[('SCR', 'Scrapped'), ('USR', 'User Submitted'), ('PRT', 'Partner')], default='USR', max_length=3),
        ),
    ]
