# Generated by Django 5.1 on 2024-11-19 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_hackathon_image_hackathon_bg_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='hackathons', to='core.hackathonlocation'),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
