# Generated by Django 5.1 on 2024-11-19 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_hackathon_venue_alter_hackathon_location'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='hackathon',
            name='start_date_lt_end_date',
        ),
        migrations.RemoveField(
            model_name='hackathon',
            name='last_scraped',
        ),
        migrations.RemoveField(
            model_name='hackathon',
            name='last_updated',
        ),
        migrations.AddConstraint(
            model_name='hackathon',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__lte', models.F('end_date'))), name='start_date_lte_end_date'),
        ),
    ]
