# Generated by Django 5.1 on 2024-11-20 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_hackathon_start_date_lt_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackathon',
            name='venue',
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='id',
            field=models.CharField(editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='hackathons', to='core.hackathonlocation'),
        ),
    ]
