# Generated by Django 5.1 on 2024-11-28 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_hackathon_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathonlocation',
            name='venue',
            field=models.CharField(blank=True, help_text='what venue is the hackathon renting (e.g. University of Toronto)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hackathonlocation',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='location', to='core.location'),
        ),
        migrations.AlterField(
            model_name='hackathonlocation',
            name='name',
            field=models.CharField(blank=True, help_text='Where the hackathon is located (e.g. Buringlont, Ontario)', max_length=255, null=True),
        ),
    ]
