# Generated by Django 5.1 on 2024-11-28 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_hackathon_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathonlocation',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='location', to='core.location'),
        ),
    ]
