# Generated by Django 5.1 on 2024-11-29 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_hackathonlocation_venue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='down_vote',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='up_vote',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
