# Generated by Django 5.1 on 2024-12-01 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_hackathon_down_vote_hackathon_up_vote'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='hackathon',
            constraint=models.UniqueConstraint(fields=('name', 'end_date'), name='unique_id'),
        ),
    ]
