# Generated by Django 5.1 on 2024-12-01 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_school_added_by_school_created_at_school_public'),
        ('core', '0018_hackathon_unique_id'),
    ]

    operations = [
    ]
