# Generated by Django 5.1 on 2024-12-02 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_merge_20241201_2004'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='hackathon',
            name='start_date_lte_end_date',
        ),
        migrations.RemoveConstraint(
            model_name='hackathon',
            name='unique_id',
        ),
        migrations.RemoveField(
            model_name='hackathon',
            name='down_vote',
        ),
        migrations.RemoveField(
            model_name='hackathon',
            name='up_vote',
        ),
    ]
