# Generated by Django 5.1 on 2024-12-02 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_hackathon_start_date_lte_end_date_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='hackathon',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__lte', models.F('end_date'))), name='start_date_lte_end_date'),
        ),
    ]
