# Generated by Django 5.1 on 2024-12-02 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_hackathon_start_date_lte_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='dup',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
