# Generated by Django 5.1 on 2024-12-02 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_hackathon_dup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='dup',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
