# Generated by Django 5.1 on 2024-12-03 03:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_hackathon_dup'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('from_hacker', models.ManyToManyField(related_name='hackathon_downvotes', to=settings.AUTH_USER_MODEL)),
                ('hackathon_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='downvotes', to='core.hackathon')),
            ],
        ),
        migrations.CreateModel(
            name='UpVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('from_hacker', models.ManyToManyField(related_name='hackathon_upvotes', to=settings.AUTH_USER_MODEL)),
                ('hackathon_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to='core.hackathon')),
            ],
        ),
    ]
