# Generated by Django 5.1 on 2024-12-04 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_downvote_upvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='count_downvotes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='count_upvotes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
