# Generated by Django 5.1 on 2024-12-04 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_hackathon_count_downvotes_hackathon_count_upvotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upvote',
            name='from_hacker',
        ),
        migrations.RemoveField(
            model_name='upvote',
            name='hackathon_id',
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_vote', models.BooleanField(default=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('from_hacker', models.ManyToManyField(related_name='hackathon_votes', to=settings.AUTH_USER_MODEL)),
                ('hackathon_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.hackathon')),
            ],
        ),
        migrations.DeleteModel(
            name='DownVote',
        ),
        migrations.DeleteModel(
            name='UpVote',
        ),
    ]
