# Generated by Django 5.1 on 2024-12-05 04:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_curatorrequest_review_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='curatorrequest',
            name='created_by',
            field=models.ManyToManyField(related_name='curator_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
