# Generated by Django 5.1 on 2024-12-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_curatorrequest_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackathon',
            name='is_diversity',
        ),
        migrations.RemoveField(
            model_name='hackathon',
            name='is_nonenglish',
        ),
        migrations.RemoveField(
            model_name='hackathon',
            name='is_over18',
        ),
        migrations.RemoveField(
            model_name='hackathon',
            name='is_restricted',
        ),
        migrations.RemoveField(
            model_name='hackathon',
            name='is_web3',
        ),
        migrations.RemoveField(
            model_name='hackathon',
            name='notes',
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='reimbursements',
            field=models.BooleanField(default=True),
        ),
    ]
