# Generated by Django 5.1.4 on 2024-12-11 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_hackathon_is_diversity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='is_diversity',
            field=models.BooleanField(default=False, help_text='Is the hackathon only for underrepresented groups'),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='is_nonenglish',
            field=models.BooleanField(default=False, help_text='Is the primary language of this hackathon not English'),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='is_restricted',
            field=models.BooleanField(default=False, help_text='Is enrollment in this hackathon restricted to only some group of people (like those enrolled in one specific school or unoversity)'),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='is_web3',
            field=models.BooleanField(default=False, help_text='Is the hackathon Web3 themed'),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='scrape_source',
            field=models.CharField(choices=[('mlh', 'MLH'), ('dev', 'Devpost'), ('eth', 'ETHGlobal'), ('hcl', 'Hack Club'), ('na', 'Not Applicable')], default='na', max_length=3),
        ),
    ]
