# Generated by Django 5.1 on 2024-12-11 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_hackathon_is_diversity_hackathon_is_nonenglish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='source',
            field=models.CharField(choices=[('SCR', 'Scraped'), ('USR', 'User Submitted'), ('PRT', 'Partner')], default='USR', max_length=3),
        ),
    ]
