# Generated by Django 5.1.4 on 2024-12-15 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_hackathon_is_diversity_hackathon_is_nonenglish_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackathon',
            name='dup',
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='reimbursements',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='source',
            field=models.CharField(choices=[('SCR', 'Scraped'), ('USR', 'User Submitted'), ('PRT', 'Partner')], default='USR', max_length=3),
        ),
    ]
