# Generated by Django 5.1 on 2024-12-14 03:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0032_alter_location_latitude_alter_location_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="hackathon",
            name="duplication_id",
            field=models.CharField(
                blank=True,
                help_text="Duplication ID for the Hackathon",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
