# Generated by Django 5.1.4 on 2024-12-15 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_hackathon_dup_alter_hackathon_reimbursements_and_more'),
        ('core', '0033_remove_hackathon_dup_hackathon_duplication_id'),
    ]

    operations = [
    ]
