# Generated by Django 5.1 on 2024-12-15 19:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_merge_20241215_0543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='hackathon_id',
            new_name='hackathon',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='from_hacker',
            new_name='hacker',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='type_vote',
            new_name='vote_type',
        ),
        migrations.AlterField(
            model_name='curatorrequest',
            name='created_by',
            field=models.ManyToManyField(related_name='curation_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
