# Generated by Django 5.1.4 on 2024-12-18 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_rename_hackathon_id_vote_hackathon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='duplication_id',
            field=models.CharField(blank=True, help_text='Duplication ID for the Hackathon', max_length=255, null=True),
        ),
    ]
