# Generated by Django 5.1.4 on 2024-12-18 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_remove_hackathon_count_downvotes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hackathon',
            old_name='count_votes',
            new_name='vote_count',
        ),
    ]
