#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python manage.py migrate --noinput
python manage.py collectstatic --noinput

gunicorn -w 1 --bind 0.0.0.0:22300 hackathons_canada.wsgi:application
