# Generated by Django 5.0.4 on 2024-04-13 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0002_category_hackathon_created_at_hackathon_created_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_id", models.CharField(max_length=255)),
                ("client_secret", models.CharField(max_length=255)),
                ("redirect_uri", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="HackathonChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("discord_id", models.CharField(blank=True, max_length=18, null=True)),
                (
                    "archived",
                    models.BooleanField(
                        default=False,
                        help_text="If the channel has been archived or not",
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True, help_text="When the channel was archived", null=True
                    ),
                ),
                (
                    "archived_time",
                    models.DurationField(
                        blank=True,
                        help_text="How long the channel was archived for",
                        null=True,
                    ),
                ),
                (
                    "hackathon",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="channel",
                        to="core.hackathon",
                    ),
                ),
            ],
        ),
    ]
