# Generated by Django 5.0.7 on 2024-07-15 01:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dischannelsaver", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hackathonchannel",
            name="discord_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
